basePath: /
definitions:
  responses.CategoryPublicResponse:
    properties:
      created_at:
        format: date-time
        type: string
      description:
        type: string
      id:
        format: uuid
        type: string
      image_url:
        example: https://example.com/image.jpg
        format: url
        type: string
      name:
        example: Electronics
        type: string
      parent_id:
        format: uuid
        type: string
      slug:
        example: electronics
        format: slug
        type: string
      updated_at:
        format: date-time
        type: string
    type: object
  responses.LanguagePublicResponse:
    properties:
      code:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.DetailResponse-responses_CategoryPublicResponse:
    properties:
      data:
        $ref: '#/definitions/responses.CategoryPublicResponse'
      translations:
        items:
          $ref: '#/definitions/types.TranslationResponse'
        type: array
    type: object
  types.DetailResponse-responses_LanguagePublicResponse:
    properties:
      data:
        $ref: '#/definitions/responses.LanguagePublicResponse'
      translations:
        items:
          $ref: '#/definitions/types.TranslationResponse'
        type: array
    type: object
  types.Envelope:
    additionalProperties: true
    type: object
  types.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  types.PaginatedResponse-responses_CategoryPublicResponse:
    properties:
      metadata:
        $ref: '#/definitions/types.PaginationMetadata'
      results:
        items:
          $ref: '#/definitions/types.DetailResponse-responses_CategoryPublicResponse'
        type: array
    type: object
  types.PaginationMetadata:
    properties:
      current_page:
        type: integer
      first_page:
        type: integer
      last_page:
        type: integer
      page_size:
        type: integer
      total_records:
        type: integer
    type: object
  types.TranslationResponse:
    properties:
      entity_id:
        format: uuid
        type: string
      field_name:
        example: name
        type: string
      id:
        format: uuid
        type: string
      language_code:
        example: ru
        type: string
      table_name:
        example: products
        type: string
      translated_field_name:
        example: название
        type: string
      translated_value:
        example: ноутбук
        type: string
    type: object
host: localhost:4000
info:
  contact:
    email: kcharymyrat@gmail.com
    name: Charymyrat Garryyev
  description: Go lang E-commerce
  license:
    name: Apache 2.0
    url: '""'
  title: E-commerce
  version: "1.0"
paths:
  /api/v1/categories:
    get:
      description: List categories with pagination and filters
      parameters:
      - description: 'Languages: en, ru, tk'
        in: header
        name: Accept-Language
        type: string
      - in: query
        name: created_at_from
        type: string
      - in: query
        name: created_at_up_to
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: created_by_ids
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: names
        type: array
      - in: query
        maximum: 10000000
        minimum: 1
        name: page
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: parent_ids
        type: array
      - in: query
        maxLength: 50
        name: search
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: slugs
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: sort_safe_list
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: sorts
        type: array
      - in: query
        name: updated_at_from
        type: string
      - in: query
        name: updated_at_up_to
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: updated_by_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PaginatedResponse-responses_CategoryPublicResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: List categories
      tags:
      - categories
  /api/v1/categories/{slug}:
    get:
      consumes:
      - multipart/form-data
      description: Get specific category details by slug
      parameters:
      - description: 'Languages: en, ru, tk'
        in: header
        name: Accept-Language
        type: string
      - description: Category Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.DetailResponse-responses_CategoryPublicResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get category by slug
      tags:
      - categories
  /api/v1/healthcheck:
    get:
      consumes:
      - application/json
      description: Returns the status of the API
      operationId: healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Envelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get health check
      tags:
      - Healthcheck
  /api/v1/languages:
    get:
      description: List languages with pagination and filters
      parameters:
      - description: 'Languages: en, ru, tk'
        in: header
        name: Accept-Language
        type: string
      - in: query
        maximum: 10000000
        minimum: 1
        name: page
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.Envelope'
            - properties:
                metadata:
                  $ref: '#/definitions/types.PaginationMetadata'
                results:
                  items:
                    $ref: '#/definitions/responses.LanguagePublicResponse'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: List languages
      tags:
      - languages
  /api/v1/languages/{id}:
    get:
      description: Get specific language details by id
      parameters:
      - description: 'Languages: en, ru, tk'
        in: header
        name: Accept-Language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: translations are empty for this endpoint
          schema:
            $ref: '#/definitions/types.DetailResponse-responses_LanguagePublicResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get language by id
      tags:
      - languages
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
