basePath: /
definitions:
  data.Category:
    properties:
      created_at:
        type: string
      created_by_id:
        type: string
      description:
        maxLength: 500
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      parent_id:
        type: string
      slug:
        type: string
      updated_at:
        type: string
      updated_by_id:
        type: string
      version:
        minimum: 1
        type: integer
    required:
    - created_at
    - created_by_id
    - id
    - image_url
    - name
    - slug
    - updated_at
    - updated_by_id
    - version
    type: object
  types.Envelope:
    additionalProperties: true
    type: object
  types.Metadata:
    properties:
      current_page:
        type: integer
      first_page:
        type: integer
      last_page:
        type: integer
      page_size:
        type: integer
      total_records:
        type: integer
    type: object
host: localhost:4000
info:
  contact:
    email: kcharymyrat@gmail.com
    name: Charymyrat Garryyev
  description: Go lang E-commerce
  license:
    name: Apache 2.0
    url: '""'
  title: E-commerce
  version: "1.0"
paths:
  /api/v1/categories:
    get:
      description: List categories with pagination and filters
      parameters:
      - in: query
        name: created_at_from
        type: string
      - in: query
        name: created_at_up_to
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: created_by_ids
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: names
        type: array
      - in: query
        maximum: 10000000
        minimum: 1
        name: page
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: parent_ids
        type: array
      - in: query
        maxLength: 50
        name: search
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: slugs
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: sort_safe_list
        type: array
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: sorts
        type: array
      - in: query
        name: updated_at_from
        type: string
      - in: query
        name: updated_at_up_to
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: string
        name: updated_by_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.Envelope'
            - properties:
                metadata:
                  $ref: '#/definitions/types.Metadata'
                results:
                  items:
                    $ref: '#/definitions/data.Category'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/types.Envelope'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/types.Envelope'
            - properties:
                error:
                  type: string
              type: object
      summary: List categories
      tags:
      - categories
  /api/v1/categories/{slug}:
    get:
      consumes:
      - multipart/form-data
      description: Get specific category details by slug
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Envelope'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.Envelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Envelope'
      summary: Get category by slug
      tags:
      - categories
  /api/v1/healthcheck:
    get:
      consumes:
      - application/json
      description: Returns the status of the API
      operationId: healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Envelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Envelope'
      summary: Get health check
      tags:
      - Healthcheck
  /api/v1/languages:
    get:
      description: List languages with pagination and filters
      parameters:
      - in: query
        maximum: 10000000
        minimum: 1
        name: page
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Envelope'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.Envelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Envelope'
      summary: List languages
      tags:
      - languages
  /api/v1/languages/{id}:
    get:
      description: Get specific language details by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Envelope'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.Envelope'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.Envelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Envelope'
      summary: Get language by id
      tags:
      - languages
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
